sudo: true
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  cleanup: false
  github_token: $GH_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: source
  local_dir: public